### ISSUE TITLE
Fix `module.exports`

### ISSUE THREAD

**Issue by StuAA78** [DEFRA/water-abstraction-team#28]
The codebase currently has a pattern of declaring exports individually, eg:

```js
exports.getBatch = getBatch;
exports.getBatches = getBatches;
exports.getBatchDownloadData = getBatchDownloadData;
exports.getBatchInvoices = getBatchInvoices;
exports.getBatchInvoiceDetail = getBatchInvoiceDetail;
exports.getBatchInvoicesDetails = getBatchInvoicesDetails;
exports.getInvoiceLicenceWithTransactions = getInvoiceLicenceWithTransactions;
exports.deleteBatchInvoice = deleteBatchInvoice;
exports.deleteBatch = deleteBatch;

exports.postApproveBatch = postApproveBatch;
exports.postCreateBatch = postCreateBatch;

exports.deleteAllBillingData = deleteAllBillingData;
exports.postSetBatchStatusToCancel = postSetBatchStatusToCancel;
```

VS Code has a handy feature which lets us jump to a function's implementation by command-clicking it, however this breaks when exports are declared as above -- they have to be defined in the more regular way instead:

```js
module.exports = {
  getBatch,
  getBatches,
  getBatchDownloadData,
  getBatchInvoices,
  getBatchInvoiceDetail,
  getBatchInvoicesDetails,
  getInvoiceLicenceWithTransactions,
  deleteBatchInvoice,
  deleteBatch,
  postApproveBatch,
  postCreateBatch,
  deleteAllBillingData,
  postSetBatchStatusToCancel
};
```

So to help us navigate the codebase, we should update how we declare our exports.

- [ ] hapi-pg-rest-api
- [ ] water-abstraction-helpers
- [x] water-abstraction-import
- [ ] water-abstraction-permit-repository
- [ ] water-abstraction-reporting
- [ ] water-abstraction-returns
- [ ] water-abstraction-service
- [ ] water-abstraction-tactical-crm
- [ ] water-abstraction-tactical-idm
- [ ] water-abstraction-ui

**Comment by Jozzey** [comment]
Started working on this issue in the imports repo. A PR has been created here: https://github.com/DEFRA/water-abstraction-import/pull/365

**Comment by Jozzey** [comment]
Attempted to update [hapi-pg-rest-api](https://github.com/DEFRA/hapi-pg-rest-api) to use this exports method but due to the odd way the HAPIRestAPI class is exported I've given up on this one for the time being.

**Comment by Cruikshanks** [comment]
When the current dev team first joined Water Abstraction we started creating issues for all the problems we saw. Whilst we were still getting to grips with the service it gave us opportunities to fix things and get stuck into the legacy code.

After a while, we became more confident and were able to get stuck into the critical feature at that time; SROC Supplementary billing. It also proved we could implement new and existing functionality in our [water-abstraction-system repo](https://github.com/DEFRA/water-abstraction-system) and integrate it with the existing apps. This, and the ongoing performance and stability issues with the legacy code have meant the whole delivery team are now onboard with us, over time, migrating _all_ functionality across.

So, as a dev team, we're instead going to focus our efforts on migrating functionality rather than fixing the legacy code. It means issues like this are now redundant as we don't intend to ever fix them.
