### ISSUE TITLE
Assertions missing from unit tests

### ISSUE THREAD

**Issue by Jozzey** [DEFRA/water-abstraction-team#48]
After renaming the test files in the [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui) as per Issue #27. SonarCloud started complaining about this issue _**"Complete this assertion; 'expect' doesn't assert anything by itself."**_  

Upon investigation it was found that SonarCloud was indeed correct, there are unit tests that have missing assertions. So effectively these unit tests aren't actually testing anything. On the ones where I tried adding the assertion I would expect most of the tests failed.

At some point these unit tests need to either be re-written correctly or removed.

An example is in `test/internal/modules/agreements/lib/helpers.test.js` currently at line 88:
```
      test('the next state is set in the session', async () => {
        expect(request.yar.set.calledWith(
          'licence.test-licence-id.create-agreement', { foo: 'bar' }
        ))
```

**Comment by Jozzey** [comment]
More assertions found to be missing as part of the PR https://github.com/DEFRA/water-abstraction-tactical-crm/pull/905

**Comment by Jozzey** [comment]
Found more assertions missing from the imports repo in this PR https://github.com/DEFRA/water-abstraction-import/pull/437 after renaming the test files

**Comment by Cruikshanks** [comment]
When the current dev team first joined Water Abstraction we started creating issues for all the problems we saw. Whilst we were still getting to grips with the service it gave us opportunities to fix things and get stuck into the legacy code.

After a while, we became more confident and were able to get stuck into the critical feature at that time; SROC Supplementary billing. It also proved we could implement new and existing functionality in our [water-abstraction-system repo](https://github.com/DEFRA/water-abstraction-system) and integrate it with the existing apps. This, and the ongoing performance and stability issues with the legacy code have meant the whole delivery team are now onboard with us, over time, migrating _all_ functionality across.

So, as a dev team, we're instead going to focus our efforts on migrating functionality rather than fixing the legacy code. It means issues like this are now redundant as we don't intend to ever fix them.
