### ISSUE TITLE
Work on queries in `src/lib/connectors/repos/queries/charge-versions.js`

### ISSUE THREAD

**Issue by StuAA78** [DEFRA/water-abstraction-team#50]
The file `src/lib/connectors/repos/queries/charge-versions.js` contains two large SQL queries. An initial look shows us that not only are they very similar (one has a few extra lines to handle supplementary bill runs) but they could potentially be rewritten to be more efficient. This issue is to investigate and rewrite them.

**Comment by Cruikshanks** [comment]
When the current dev team first joined Water Abstraction we started creating issues for all the problems we saw. Whilst we were still getting to grips with the service it gave us opportunities to fix things and get stuck into the legacy code.

After a while, we became more confident and were able to get stuck into the critical feature at that time; SROC Supplementary billing. It also proved we could implement new and existing functionality in our [water-abstraction-system repo](https://github.com/DEFRA/water-abstraction-system) and integrate it with the existing apps. This, and the ongoing performance and stability issues with the legacy code have meant the whole delivery team are now onboard with us, over time, migrating _all_ functionality across.

So, as a dev team, we're instead going to focus our efforts on migrating functionality rather than fixing the legacy code. It means issues like this are now redundant as we don't intend to ever fix them.
