### ISSUE TITLE
Refactor `src/modules/billing/services/batch-service.js`

### ISSUE THREAD

**Issue by StuAA78** [DEFRA/water-abstraction-team#51]
We spotted some potential areas of refactoring while investigating `src/modules/billing/services/batch-service.js`:

- [ ] If our understanding is correct then the calculation `fromFinancialYearEnding = config.billing.alcsEndYear - (config.billing.supplementaryYears + (config.billing.alcsEndYear - toFinancialYearEnding))` on line 271 gives exactly the same result `toFinancialYearEnding - config.billing.supplementaryYears`. We could therefore simplify it to this.
- [ ] `config.billing.alcsEndYear` and `config.billing.supplementaryYears` will never change from their current values of `2022` and `5`, and they are not used anywhere else in the code. We could therefore replace them with constants.
- [ ] The function `_alcsToFinancialYearEndingCheck` is used to cap the value of `toFinancialYearEnding` at `config.billing.alcsEndYear`. To simplify things we could replace it with `Math.min(toFinancialYearEnding, config.billing.alcsEndYear)`

**Comment by Cruikshanks** [comment]
When the current dev team first joined Water Abstraction we started creating issues for all the problems we saw. Whilst we were still getting to grips with the service it gave us opportunities to fix things and get stuck into the legacy code.

After a while, we became more confident and were able to get stuck into the critical feature at that time; SROC Supplementary billing. It also proved we could implement new and existing functionality in our [water-abstraction-system repo](https://github.com/DEFRA/water-abstraction-system) and integrate it with the existing apps. This, and the ongoing performance and stability issues with the legacy code have meant the whole delivery team are now onboard with us, over time, migrating all functionality across.

So, as a dev team, we will focus our efforts on migrating functionality rather than fixing the legacy code. It means issues like this are now redundant as we don't intend to fix them.
